meal:
  '*': 'meal#decimal'
votes:
  negative:
    '*': 'negative#decimal'
  positive:
    '*': 'positive#decimal'
title:
  '*': ''
subtitle:
  '*': ''
category:
  '*': ''
body:
  '*': ''
username:
  '*': ''
userlink:
  '*': ''
created_date:
  '*': 'created_date#isodate'
updated_date:
  '*': 'updated_date#isodate'
annotations:
- '*': ''
  created_date:
    '*': 'created_date#isodate'
  text:
    '*': ''
  username:
    '*': ''
  userlink:
    '*': ''
author:
  userlink_guess:
    '*': ''
  username:
    '*': ''
links:
- '*': ''
  '-':
    '*': ''
  created_date:
    '*': 'created_date#isodate'
  text:
    '*': ''
  updated_date:
    '*': 'updated_date#isodate'
  userlink:
    '*': ''
  username:
    '*': ''
media:
  post_image:
    '*': ''
